spring.application.name=booking-service

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BookingDb;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Chronos!2026

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.flyway.enabled=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=chronos
spring.rabbitmq.password=Chronos!2026